name: Tests

on:
  push:
    branches:
      - main
  
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432

    env:
      DB_URL: ${{ secrets.TEST_DB_URL }}
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14.6"

      - name: Install dependencies
        working-directory: backend
        run: |
          pip install -r requirements.txt
        
      - name: Run pytest
        working-directory: backend
        run: |
          export PYTHONPATH='.'
          pytest

  deploy:
      needs: test
      runs-on: ubuntu-latest
      steps:
          - name: Trigger Render
            run: curl '${{ secrets.RENDER_DEPLOY_HOOK }}'

